# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3a7c6a4f09e0937beb8ba9522d62fdf54df24626ab6622994821c60f86fd27d0fb7085711f62c40c1848744e21035a73cc46dd946b82a890b035cf0281f59e83

test:
  secret_key_base: 89ffcf84f9e48a5c0c57339847c152276921bc8a0aedb93dc8f188b7b16c10fb8ccf6e46f08bfb9d6d8db960f76a2e3f405a037bb56ee62f0d0ebac7b484eac7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV['SECRET'] %>
